export { default as ClosedMenuIcon } from "./icons/ClosedMenuIcon";
export { default as OpenMenuIcon } from "./icons/OpenMenuIcon";
export { default as SoundWavesIcon } from "./icons/SoundWavesIcon";
export { default as PlayIcon } from "./icons/PlayIcon";
export { default as SingleSongIcon } from "./icons/SingleSongIcon";
export { default as CloseIcon } from "./icons/CloseIcon";
export { default as AlbumIcon } from "./icons/AlbumIcon";
export { default as InfoIcon } from "./icons/InfoIcon";
export { default as GameControlIcon } from "./icons/InfoIcon";
